name: Deploy to Kubernetes
on:
    push:
        branches:
            - main
            - Complete-CI/CD-with-Terraform-GKE
            - destroy-branch  # Specify the branch that triggers destruction
    workflow_dispatch:  # Allows manual triggering of the destroy job

env:
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_TAG: ${{ github.sha }}
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            - uses: 'actions/checkout@v3'
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v1'
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/583709996454/locations/global/workloadIdentityPools/k8s-pool-new/providers/k8s-provider'
                service_account: 'tf-gke-test@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'
            - name: Docker auth
              run: gcloud auth configure-docker
            - run: gcloud auth list
            - name: Build and push docker image
              run: |
                  docker build -t us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG .
                  docker push us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG
              working-directory: ./nodeapp
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
            - name: Terraform init
              run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s-test"
              working-directory: ./terraform
            - name: Terraform Plan
              run: |
                  terraform plan \
                  -var="region=us-central1" \
                  -var="project_id=$GCP_PROJECT_ID" \
                  -var="container_image=us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG" \
                  -out=PLAN
              working-directory: ./terraform
            - name: Terraform Apply
              run: terraform apply PLAN
              working-directory: ./terraform

    destroy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/destroy-branch'  # Only run this job on the specified branch
        steps:
            - uses: 'actions/checkout@v3'
            - id: 'auth-destroy'
              name: 'Authenticate to Google Cloud for Destroy'
              uses: 'google-github-actions/auth@v1'
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/583709996454/locations/global/workloadIdentityPools/k8s-pool-new/providers/k8s-provider'
                service_account: 'tf-gke-test@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
            - name: Setup Terraform for Destroy
              uses: hashicorp/setup-terraform@v2
            - name: Terraform init for Destroy
              run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s-test"
              working-directory: ./terraform
            - name: Terraform Destroy
              run: terraform destroy -auto-approve \
                  -var="region=us-central1" \
                  -var="project_id=$GCP_PROJECT_ID"
              working-directory: ./terraform
